name: FitTrack
options:
  bundleIdPrefix: com.henrique
settings:
  base:
    SDKROOT: iphoneos
    CODE_SIGNING_ALLOWED: NO
targets:
  FitTrack:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - App
      - fitnessapp
    info:
      path: fitnessapp/Info.plist
